apiVersion: v1
kind: Service
metadata:
  namespace: jenkins-system
  name: jenkins-cluster
spec:
  selector:
    app: jenkins-cluster
  ports:
    - name: jenkins-cluster
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort
